=begin

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten 
terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

=end
$myLog = open('PE12.log', 'w')
$myLog << "NUM  |  SIZE   \n"
$myLog << "----------------------------- \n"

def number_of_factors_in(num)
  factors = 0
  limit = Math.sqrt(num)
  for i in (1..limit)
    if num % i == 0
      factors += 2
    end
  end
  #puts factors
  $myLog << "#{num}  |  #{factors} \n"
  puts "#{num}  |  #{factors} \n"
  return factors
end

def triangle_with_over_five_hundred_divisors
  anchor = 1
  i = 1
  
  while true
    num_of_factors = number_of_factors_in(anchor)
    if num_of_factors > 500
      return num_of_factors
    end
    
    i += 1
    anchor += i
  end
end

def factors_in_triangle(n, anchor)
  count = 0
  for i in (1..anchor)
    if anchor % i == 0
      count += 1
    end
  end
  
  if count > 500
    return anchor
  end
  $myLog << "#{anchor}  |  #{count} \n"
  puts "#{anchor}  |  #{count} \n"
  return factors_in_triangle(n+1, anchor += n)
end


puts "The triangle with over 500 divisiors: #{triangle_with_over_five_hundred_divisors}"
# puts "The triangle with over 500 divisiors: #{factors_in_triangle(4270, 9114315)}"

