# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

upperBound = 4000000
sumOfEvenFibs = 0

fibA = 0
fibB = 1

while sumOfEvenFibs <= upperBound
  tmpSum = fibA + fibB
  if tmpSum % 2 == 0
    sumOfEvenFibs += tmpSum
  end
  
  fibA = fibB
  fibB = tmpSum
end

puts 'Sum of even Fibonacci numbers less than four million: ' + sumOfEvenFibs.to_s