//
//  main.m
//  PE2
//
//  Created by Matthew on 6/30/13.
//  Copyright (c) 2013 Matthew. All rights reserved.
//

#import <Foundation/Foundation.h>

int main(int argc, const char * argv[])
{

    @autoreleasepool {
        
        /*
         
         Each new term in the Fibonacci sequence is generated by adding the previous two terms.
         By starting with 1 and 2, the first 10 terms will be:
         
         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         
         By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         
         */
        
        int upperBound = 4000000;
        
        int fibA = 0;
        int fibB = 1;
        int tmpSum = 0;
        
        int sumOfEvenFibs = 0;
        
        while (sumOfEvenFibs < upperBound) {
            tmpSum = fibA + fibB;
            
            if (tmpSum % 2 == 0) {
                sumOfEvenFibs += tmpSum;
            }
            
            fibA = fibB;
            fibB = tmpSum;
        }
        
        NSLog(@"Sum of even Fibs less than 4,000,000 is: %d", sumOfEvenFibs);
        
    }
    return 0;
}

